const en = {
  appName: "Antigravity Switcher",
  common: {
    loading: "Loading...",
    error: "Error",
    unknown: "Unknown",
    notAvailable: "N/A",
    openMenu: "Open menu",
    cancel: "Cancel",
  },
  status: {
    checking: "Checking status...",
    running: "Antigravity is running in background",
    stopped: "Antigravity service stopped",
    services: "Services",
    apps: "Applications",
    antigravity: "Antigravity Runtime",
    relay: "Relay Server",
    tunnel: "Cloudflare Tunnel",
    dashboard_title: "Service status",
    open_dashboard: "Open service status",
    checking_short: "Checking...",
    running_short: "Running",
    stopped_short: "Stopped",
    all_running: "All services running",
    all_stopped: "All services stopped",
    partial_running: "{{running}}/{{total}} services running",
    not_installed_short: "Not Installed",
    tunnel_not_installed_tooltip:
      "cloudflared CLI is not installed on this computer",
    wifi_network: "Wi-Fi",
    local_network: "Local",
    service_relay: "Relay Server",
    service_tunnel: "Cloudflare Tunnel",
    service_app: "Antigravity App",
    service_ide: "Antigravity IDE",
    service_cli: "Antigravity CLI",
    tooltips: {
      appNotInstalled: "Antigravity App is not detected on this system",
      ideNotInstalled: "Antigravity IDE is not detected on this system",
      cliNotInstalled:
        "Antigravity CLI executable is not found in PATH or standard directories",
      tunnelNotInstalled: "cloudflared CLI is not installed on this computer",
      cliIdleGuidance: "Run directly from terminal via 'agy <command>'",
    },
  },
  action: {
    stop: "Stop",
    start: "Start",
    switch: "Switch",
    deleteBackup: "Delete Backup",
    backupCurrent: "Backup Current",
    retry: "Retry",
    details: "Details",
    openLogs: "Open Log Directory",
    cancel: "Cancel",
  },
  update: {
    title: "Updates",
    checking: "Checking...",
    checkNow: "Check for Updates",
    checkFailed: "Unable to check for updates",
    upToDate: "You're up to date.",
    unsupported: "Automatic update checks are not available on this platform.",
    available: {
      title: "Update available",
      description: "Version {{version}} is available on GitHub.",
      download: "Download",
      downloading: "Downloading...",
      dismiss: "Dismiss",
      macosUnsignedNote:
        "This macOS build is not officially signed. If macOS blocks the app, follow the manual signing steps in the GitHub README or related issues.",
    },
    downloaded: {
      title: "Update ready",
      description: "Version {{version}} has been downloaded.",
      restart: "Restart",
    },
  },
  error: {
    generic: "An unexpected error occurred.",
    detailsTitle: "Error details",
    detailsDescription:
      "Backend error details are shown below. They may include local file paths and stack frames.",
    keychainUnavailable: "Keychain is unavailable.",
    keychainHint: {
      translocation:
        "Detected macOS App Translocation. Move the app to /Applications and reopen.",
      keychainDenied:
        "Keychain access denied. The app may be unsigned; see README for the self-signing workaround.",
      signNotarize: "Please use a signed and notarized build when available.",
    },
    dataMigrationFailed: "Unable to decrypt legacy account data.",
    masterKeyUnavailable:
      "Stored accounts were found, but their encryption key is currently unavailable. No account data or key files were changed.",
    dataMigrationHint: {
      relogin: "Please re-login or re-add your accounts.",
      clearData:
        "If the issue persists, clear local account data and sign in again.",
    },
    antigravityStorageJsonNotFound:
      "Antigravity storage.json was not found. Open the target Antigravity app and sign in once, then try switching again.",
    antigravityProjectIdMissing:
      "This account is missing an Antigravity project ID. This may happen if the account has not signed in to the Antigravity app before. Please sign in once in the Antigravity app, then return to this tool and try switching again.",
    antigravityDatabasePermissionDenied:
      "Antigravity database storage is not writable. Check the configured Antigravity user-data directory or restart Antigravity Switcher after opening Antigravity once.",
    cloudAccountLoginExpired:
      "The login information for this cloud account has expired. Please log in again.",
    rootBoundary: {
      title: "Application Encountered an Error",
      description:
        "A critical unexpected error occurred. You can reload the application window to restore normal operation.",
      reload: "Reload Application",
      copyDetails: "Copy Error Details",
      detailsCopied: "Error details copied to clipboard.",
      viewDetails: "View Technical Diagnostics",
      hideDetails: "Hide Technical Diagnostics",
    },
    routeFallback: {
      title: "Unable to Load Section",
      description: "An unexpected rendering error occurred in this view.",
      retry: "Retry Section",
      goHome: "Return to Accounts",
    },
  },
  nav: {
    accounts: "Accounts",
    relay: "Remote Relay",
    context: "Chat Context",
    settings: "Settings",
  },
  remote: {
    title: "Remote Control & Mobile Tethering",
    subtitle:
      "Decoupled Fastify relay server and Cloudflare tunnel supervisor for uninterrupted mobile supervision",
  },
  relay: {
    title: "Local Relay Server",
    subtitle: "Local WebSocket command bridge and static PWA host",
    statusActive: "Active",
    statusInactive: "Inactive",
    statusStarting: "Starting...",
    statusStopping: "Stopping...",
    port: "Port: {{port}}",
    toggleStart: "Start Relay Server",
    toggleStop: "Stop Relay Server",
    bufferLabel: "Command Buffer",
    bufferCount: "{{count}} queued commands",
    bufferEmpty: "Buffer empty (0 queued)",
    upstreamTitle: "Upstream Daemon Bridge",
    upstreamConnected: "Connected",
    upstreamReconnecting: "Reconnecting",
    upstreamBuffering: "Buffering",
    upstreamOffline: "Offline",
    startFailed: "Failed to start relay server: {{error}}",
    stopFailed: "Failed to stop relay server: {{error}}",
    mirrorBoundary: {
      title: "Remote Mirror Scope Notice",
      badge: "App & IDE Only",
      description:
        "The Mobile Remote Mirror streams Antigravity App and Antigravity IDE sessions only. Antigravity CLI runs exclusively in your terminal and cannot be mirrored to mobile companion devices.",
      callout:
        "Antigravity CLI operates directly on this host and is not mirrored to mobile devices.",
    },
  },
  tunnel: {
    title: "Cloudflare Quick Tunnel",
    subtitle: "Secure public HTTPS/WSS tunnel via trycloudflare.com",
    statusConnected: "Connected",
    statusStarting: "Establishing Tunnel...",
    statusReconnecting: "Reconnecting Tunnel...",
    statusStopped: "Stopped",
    statusError: "Tunnel Error",
    urlLabel: "Public Tunnel URL",
    urlPlaceholder: "Waiting for tunnel assignment...",
    copyUrl: "Copy Tunnel URL",
    urlCopied: "Tunnel URL copied to clipboard",
    restartTunnel: "Restart Tunnel",
    restarting: "Restarting...",
    stop: "Stop Tunnel",
    stopping: "Stopping...",
    start: "Start Tunnel",
    starting: "Starting...",
    restartFailed: "Failed to restart tunnel: {{error}}",
    pid: "Process PID: {{pid}}",
    startFailed: "Failed to start Cloudflare tunnel: {{error}}",
    stopFailed: "Failed to stop Cloudflare tunnel: {{error}}",
    notInstalledBadge: "Not Installed",
    missingBannerTitle: "cloudflared CLI Not Found",
    missingBannerDesc:
      "Cloudflare Quick Tunnel requires the cloudflared executable to establish public secure tunnels for mobile remote access.",
    installCommandLabel: "Recommended installation command for {{platform}}:",
    installCommandLabelGeneric: "Installation command:",
    copyCommand: "Copy",
    copied: "Copied",
    commandCopied: "Command copied to clipboard",
    checkAgain: "Check Again",
    checking: "Checking...",
    binaryDetectedSuccess: "cloudflared CLI found at {{path}}",
    binaryStillMissing:
      "cloudflared is still not found in PATH or standard directories",
    officialDocs: "Official Documentation",
    startDisabledReason:
      "Cannot start tunnel because cloudflared executable is not installed on this system",
    missingTooltip:
      "cloudflared executable is missing. Please install it to enable remote tunneling.",
    binaryNotInstalledTooltip:
      "cloudflared CLI is not installed on this computer",
  },
  pairing: {
    title: "Mobile Pairing & QR Access",
    subtitle:
      "Scan with your phone camera to open the remote control companion",
    qrAlt: "QR Code for pairing mobile remote control",
    scanInstructions: "Scan with phone camera to connect",
    scanTip:
      "Scan this QR code with your mobile device camera to open the companion PWA.",
    securityNotice:
      "Pairing URL includes an ephemeral one-time authentication key. Do not share.",
    regenerateToken: "Regenerate Pairing Key",
    tokenLabel: "Pairing Key",
    copyToken: "Copy Key",
    tokenCopied: "Pairing key copied to clipboard",
    modeTunnel: "Cloudflare Tunnel",
    modeWifi: "Local Wi-Fi",
    wifiAdvisory: "Connect your phone to the same Wi-Fi network to access.",
    copyLink: "Copy Link",
    linkCopied: "Pairing link copied to clipboard",
    serverInactive: "Relay Server Inactive",
    startServerToPair: "Start relay server to enable mobile pairing",
    keySingleUseBadge: "Single-Use Per Device",
    autoRegeneratedNotice:
      "Pairing key auto-regenerated after device connection",
    keyConsumedError:
      "This pairing key has already been consumed by another device. Please get a fresh key from the desktop host.",
    keyInvalidError:
      "Invalid pairing key. Please verify the active key on your desktop dashboard.",
    platformScopeNotice:
      "Mobile companion mirrors Antigravity App and Antigravity IDE sessions. Antigravity CLI is not supported.",
  },
  sessions: {
    title: "Connected Phone Sessions",
    subtitle:
      "Active mobile remote control connections authorized via the local relay",
    countSingular: "1 session",
    countPlural: "{{count}} sessions",
    countAria: "{{count}} paired sessions",
    colDevice: "Device / Client",
    colIp: "IP Address",
    colDuration: "Connected For",
    colLastActive: "Last Active",
    colActions: "Actions",
    deviceIdTooltip: "Device ID: {{id}} (click to copy)",
    copyDeviceIdAria: "Copy device ID {{id}}",
    deviceIdCopied: "Device ID copied to clipboard",
    relativeJustNow: "just now",
    relativeSecondsAgo: "{{count}}s ago",
    relativeMinutesAgo: "{{count}}m ago",
    relativeHoursAgo: "{{count}}h ago",
    deviceAndroid: "Android Device",
    deviceIPhone: "iPhone",
    deviceIPad: "iPad",
    deviceMac: "Mac",
    deviceWindows: "Windows PC",
    deviceLinux: "Linux PC",
    unknownDevice: "Mobile Device",
    unknownBrowser: "Web Browser",
    revoke: "Revoke",
    revoking: "Revoking...",
    revokeTooltip: "Terminate session and drop connection",
    revokeAriaLabel: "Revoke session for {{device}} on {{ip}}",
    confirmRevokeTitle: "Revoke Mobile Session?",
    confirmRevokeMessage:
      "Are you sure you want to revoke the session for {{device}} ({{ip}})? The mobile connection will be disconnected immediately.",
    confirmRevokeAction: "Confirm Revoke",
    emptyTitle: "No connected mobile devices",
    emptyDescription:
      "Scan the pairing QR code above with your smartphone to tether your first remote session.",
    revokedToast: "Session for {{device}} has been revoked",
    revokeFailed: "Failed to revoke session: {{error}}",
  },
  revocation: {
    screenHeading: "Access Revoked by Host",
    screenDescription:
      "This device session has been terminated by the desktop host. Please enter a valid pairing key to re-establish your connection.",
    overlayBadge: "Disconnected by Host",
    inputLabel: "New Pairing Key",
    inputPlaceholder: "Enter fresh pairing key",
    reconnectButton: "Reconnect Device",
    reconnecting: "Authenticating...",
    reconnectedSuccess: "Device re-connected successfully!",
    reconnectButtonAria:
      "Submit new pairing key to reconnect this revoked device",
    staleKeyError:
      "The previous pairing key is no longer valid. Enter the newly generated key shown on the desktop dashboard.",
    emptyKeyError: "Please enter a pairing key before submitting.",
    rateLimitedError:
      "Too many pairing attempts. Please wait a moment before trying again.",
    networkError:
      "Unable to reach the relay server. Please check your network connection.",
    syncingSiblingTabs:
      "Device re-paired successfully. Synchronizing open tabs...",
    fallbackTitle: "Session Revoked - Antigravity Switcher",
    fallbackNotice:
      "Session Revoked: Access was revoked by the desktop host. Please enter a valid pairing key to re-establish your connection.",
  },
  traySync: {
    switchedTitle: "Account Switched",
    switchedDescription:
      "Active account switched to {{email}} via system tray.",
    switchedAllTitle: "All Environments Switched",
    switchedAllDescription:
      "Switched all environments to {{email}} via system tray.",
    switchedTargetTitle: "Account Switched",
    switchedTargetDescription:
      "Switched {{target}} to {{email}} via system tray.",
  },
  autoSwitch: {
    toastTitle: "Auto-Switch: Rate Limit",
    toastTargetTitle: "Auto-Switch: {{target}}",
    toastAllDescription:
      "Switched all environments to {{email}} due to rate limit.",
    toastTargetDescription:
      "Switched {{target}} to {{email}} due to rate limit.",
    toastQuotaDescription:
      "Switched all environments to {{email}} due to quota exhaustion.",
    toastGenericDescription:
      "Switched all environments to {{email}} automatically.",
  },
  account: {
    current: "Current",
    lastUsed: "Last used {{time}}",
    switchToAntigravity: "Switch to Antigravity",
    switchToIde: "Switch to Antigravity IDE",
  },
  home: {
    title: "Accounts",
    description: "Manage your Antigravity Google Gemini accounts.",
    noBackups: {
      title: "No backups found",
      description:
        "Create a backup of your current Antigravity account to get started.",
      action: "Backup Current Account",
    },
  },
  settings: {
    "weekly-warmup": {
      error: "Warmup settings could not be loaded or saved.",
      retry: "Retry",
      "cost-notice":
        "Warmup uses real model quota and may use AI credits. HTTP acceptance does not guarantee a new weekly timer.",
      title: "Weekly quota warmup",
      description:
        "After a selected weekly quota resets, send one minimal request per quota bucket and record successful cycles.",
      enabled: "Enable weekly quota warmup",
      groups: "Quota groups to warm up",
      group: { claude: "Claude quota groups", gemini: "Gemini quota groups" },
    },
    title: "Settings",
    description: "Manage application preferences.",
    general: "General",
    connection: "Connection",
    models: "Models",
    appearance: {
      title: "Appearance",
      description: "Customize how Antigravity Switcher looks on your device.",
    },
    darkMode: "Dark Mode",
    darkModeDescription: "Enable dark mode for better viewing at night.",
    language: {
      title: "Language",
      description: "Select your preferred language.",
      english: "English",
      chinese: "Chinese (Simplified)",
      russian: "Russian",
      vietnamese: "Vietnamese",
      turkish: "Turkish",
      french: "French",
      indonesian: "Bahasa Indonesia",
    },
    about: {
      title: "About",
      description: "Application information.",
    },
    cache: {
      title: "Antigravity App Cache",
      description:
        "Clear known Antigravity App cache directories to resolve login or version validation issues.",
      clear: "Clear Antigravity App Cache",
      dialogTitle: "Clear Antigravity App Cache?",
      dialogDescription:
        "The following existing cache directories will be removed.",
      pathsLabel: "Cache directories",
      noPaths: "No known Antigravity App cache directories were found.",
      warning:
        "Close Antigravity App before clearing its cache to avoid locked or recreated files.",
      cancel: "Cancel",
      confirm: "Clear Cache",
      clearing: "Clearing...",
      clearedTitle: "Cache cleared",
      clearedDescription:
        "{{size}} MB was removed from Antigravity App cache directories.",
      failedTitle: "Failed to clear cache",
      notFoundTitle: "No Antigravity App cache found",
    },
    conversationCleaner: {
      title: "Broken Chat Cleaner",
      description:
        "Scan and remove orphaned chat entries whose trajectory database files were pruned, resolving 'Conversation unavailable' errors.",
      scanAndClean: "Clean Broken Chats",
      dialogTitle: "Clean Broken Chats?",
      dialogDescription:
        "Scan conversation database for orphaned entries missing their local trajectory data.",
      targetToggleLabel: "Target Environment",
      targetApp: "App (Antigravity 2.0)",
      targetIde: "IDE (Antigravity IDE)",
      targetCli: "CLI (agy)",
      scanning: "Scanning conversations...",
      scanningAria: "Scanning conversation records and local storage files",
      totalLabel: "Total registered",
      validLabel: "Intact",
      invalidLabel: "Broken",
      noInvalidChats:
        "All registered chats have valid local data. No cleanup needed.",
      zeroStateSubtext:
        "Your conversation history is fully synchronized across this environment.",
      hasInvalidChats:
        "{{count}} broken chat entries found without local trajectory data.",
      warning:
        "Restart Antigravity after pruning to refresh the conversation list.",
      cancel: "Cancel",
      confirm: "Prune Broken Chats",
      pruning: "Pruning...",
      successTitle: "Cleaned broken chats",
      successDescription:
        "Successfully pruned {{count}} orphaned chat entries.",
      failedTitle: "Failed to clean chats",
      failedDescription:
        "The conversation store could not be updated. Please ensure Antigravity is idle and try again.",
      notFoundTitle: "Conversation database not found",
      notFoundDescription:
        "No conversation database was detected for the selected environment.",
      errorTitle: "Database locked or inaccessible",
      errorDescription:
        "The conversation database is currently in use by another process. Please wait a moment and try again.",
      retry: "Retry Scan",
      projectGroupsTitle: "Affected Projects",
      noWorkspaceGroup: "Global / No Workspace",
      untitledConversation: "Untitled Conversation",
      brokenCountBadge: "{{count}} broken",
      showChats: "Show conversations",
      hideChats: "Hide conversations",
      toggleProjectAria: "Toggle conversation list for {{project}}",
    },
    version: "Version",
    platform: "Platform",
    license: "License",
    openLogDir: "Open",
    toast: {
      saved: {
        title: "Settings saved",
        description: "Your configuration has been updated.",
      },
      saveFailed: {
        title: "Error saving settings",
      },
    },
    account: {
      title: "Account Settings",
      description: "Configure automatic account refresh and sync.",
      auto_refresh: "Auto Refresh Quota",
      auto_refresh_desc: "Periodically refresh quota info for all accounts",
      auto_sync: "Auto Sync Current Account",
      auto_sync_desc: "Periodically sync active account information",
      antigravity_executable: "Antigravity App Executable",
      antigravity_executable_desc:
        "Optional path used to find portable mode data and launch Antigravity App.",
      antigravity_executable_placeholder:
        "Example: C:\\Program Files\\Antigravity\\Antigravity.exe",
      antigravity_args: "Antigravity App Launch Arguments",
      antigravity_args_desc:
        "Optional arguments passed when launching Antigravity App, such as --user-data-dir.",
      antigravity_args_placeholder:
        "Example: --user-data-dir D:\\AntigravityProfile",
      detect_antigravity_args: "Detect",
    },
    runtimes: {
      title: "Environment Runtimes",
      description:
        "Configure executable paths and launch arguments for Antigravity desktop environments.",
      target_app: "Antigravity App",
      target_ide: "Antigravity IDE",
      target_cli: "Antigravity CLI (agy)",
      browse: "Browse",
      clear: "Clear",
      detect: "Detect",
      detecting: "Detecting...",
      auto_detect_all: "Auto-Detect All",
      auto_detect_all_aria: "Auto-detect all installed Antigravity executables",
      detect_exec: "Detect",
      app: {
        title: "Antigravity App",
        executable: "Antigravity App Executable",
        executable_desc:
          "Path used to find portable mode data and launch Antigravity App.",
        executable_placeholder:
          "Example: C:\\Program Files\\Antigravity\\Antigravity.exe",
        args: "Antigravity App Launch Arguments",
        args_desc:
          "Optional arguments passed when launching Antigravity App, such as --user-data-dir.",
        args_placeholder: "Example: --user-data-dir D:\\AntigravityProfile",
        browse_aria: "Browse for Antigravity App executable",
        clear_path_aria: "Clear Antigravity App executable path",
        clear_args_aria: "Clear Antigravity App launch arguments",
        detect_args: "Detect",
        detect_args_aria:
          "Detect launch arguments from running Antigravity App",
        detect_exec_aria: "Detect installed Antigravity App executable",
      },
      ide: {
        title: "Antigravity IDE",
        executable: "Antigravity IDE Executable",
        executable_desc:
          "Path used to locate and launch portable or custom Antigravity IDE installations.",
        executable_placeholder:
          "Example: D:\\Tools\\AntigravityIDE\\AntigravityIDE.exe",
        args: "Antigravity IDE Launch Arguments",
        args_desc:
          "Optional arguments passed when launching Antigravity IDE, such as custom data or extension directories.",
        args_placeholder:
          "Example: --user-data-dir D:\\Tools\\AntigravityIDE\\data",
        browse_aria: "Browse for Antigravity IDE executable",
        clear_path_aria: "Clear Antigravity IDE executable path",
        clear_args_aria: "Clear Antigravity IDE launch arguments",
        detect_args: "Detect",
        detect_args_aria:
          "Detect launch arguments from running Antigravity IDE",
        detect_exec_aria: "Detect installed Antigravity IDE executable",
      },
      cli: {
        title: "Antigravity CLI (agy)",
        executable: "Antigravity CLI (agy) Executable",
        executable_desc:
          "Path used to locate the agy command-line binary when not present in system PATH.",
        executable_placeholder:
          "Example: /usr/local/bin/agy or ~/.local/bin/agy",
        browse_aria: "Browse for Antigravity CLI executable",
        clear_path_aria: "Clear Antigravity CLI executable path",
        detect_exec_aria: "Detect installed Antigravity CLI (agy) executable",
      },
      toast: {
        success_title: "Arguments Detected",
        success_desc:
          "Detected and applied launch arguments from running {{target}}.",
        empty_title: "Default Arguments Active",
        empty_desc:
          "{{target}} is running with default arguments (none detected).",
        not_running_title: "Process Not Running",
        not_running_desc:
          "No running {{target}} process detected. Existing arguments preserved.",
        error_title: "Detection Failed",
        error_desc:
          "Could not inspect running process arguments for {{target}}.",
        exec_detected_title: "Executable Detected",
        exec_detected_desc: "Detected and configured {{target}} at {{path}}.",
        exec_not_found_title: "Executable Not Found",
        exec_not_found_desc:
          "No installed {{target}} executable found on your system.",
        exec_already_set_title: "Already Configured",
        exec_already_set_desc:
          "{{target}} is already set to the detected path.",
        exec_preserved_title: "Path Preserved",
        exec_preserved_desc: "Existing {{target}} path preserved.",
        exec_bulk_summary_title: "Auto-Detection Complete",
        exec_bulk_summary_desc: "Configured {{count}} runtime executable(s).",
        exec_bulk_unchanged_desc:
          "All installed runtimes are already configured.",
        exec_bulk_none_desc:
          "No installed Antigravity executables detected on this system.",
      },
      dialog: {
        replace_title: "Replace Executable Path?",
        replace_desc:
          "Replace the configured path for {{target}} with the detected path?",
        batch_title: "Conflicting Executable Paths",
        batch_desc:
          "Detected paths differ from existing configurations. Select the paths you want to replace.",
        current_label: "Current Path",
        detected_label: "Detected Path",
        replace_all: "Replace All",
        replace_selected: "Replace Selected",
        keep_current: "Keep Current",
      },
    },
    startup: {
      title: "Startup",
      description: "Control application launch behavior at system startup.",
      auto_startup: "Start with system",
      auto_startup_desc:
        "Launch at sign-in and keep the app in the system tray",
      start_in_tray: "Start in tray",
      start_in_tray_desc: "Start the application minimized in the system tray",
      macos_hint:
        "macOS requires a signed app for Login Items to work. If auto-start fails, please sign the app or enable it manually in System Settings.",
    },
    notifications: {
      title: "Notifications",
      description: "Configure desktop alerts for account events.",
      quotaAlert: "Low Quota Alerts",
      quotaAlertDesc:
        "Get notified when a model quota drops below the set threshold",
      quotaThreshold: "Alert Threshold",
      quotaThresholdDesc: "Percentage below which to trigger an alert",
      saveFailed: "Failed to save notification settings",
      thresholdSaveFailed: "Failed to save threshold setting",
      aiCreditsAlert: "Low AI Credits Alert",
      aiCreditsAlertDesc:
        "Get notified when the AI credits balance falls at or below the set amount",
      aiCreditsThreshold: "AI Credits Alert Threshold",
      aiCreditsThresholdDesc:
        "Credit amount at or below which to trigger an alert",
      aiCreditsThresholdSaveFailed:
        "Failed to save AI credits threshold setting",
    },
    proxy: {
      title: "Upstream Proxy",
      description:
        "Configure a proxy for outgoing requests to Google/Gemini APIs.",
      enable: "Enable Upstream Proxy",
      url: "Proxy URL",
      timeout: "Request Timeout (Seconds)",
    },
    modelMapping: {
      title: "Model Mapping",
      description:
        "Map Claude Code models to Antigravity models. Optimize cost and speed by routing requests intelligently.",
      claudeKeyword: "Claude Model (Keyword)",
      targetGemini: "Target Gemini Model",
      addPlaceholderKey: "e.g. op-3",
      addPlaceholderValue: "e.g. gemini-3-flash",
      noMappings: "No custom mappings defined.",
      mapsTo: "Maps to",
      default: "Default",
      restoreDefaults: "Restore Defaults",
    },
    modelVisibility: {
      title: "Model Visibility",
      description:
        "Control which models are visible in account cards. Hidden models won't appear in the quota display.",
      searchPlaceholder: "Search models...",
      showAll: "Show All",
      hideAll: "Hide All",
      reset: "Reset to Defaults",
      save: "Save Changes",
      noModels: "No models found",
      modelsShown: "{{visible}} of {{total}} models visible",
      quotaManagement: "Quota Management",
      hidden: "Hidden",
      noModelsFound: "No models found",
      totalModels: "Total",
      visibleModels: "Visible",
      hiddenModels: "Hidden",
      saving: "Saving...",
    },
    autoSwitchModels: {
      title: "Auto-Switch Models Config",
      description:
        "Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.",
      searchPlaceholder: "Search models...",
      noModels: "No models found.",
      noModelsFound: "No models found.",
      includeLabel: "Include",
      priorityLabel: "Priority",
      save: "Save Config",
      saving: "Saving...",
      saved: "Auto-switch model configuration saved successfully.",
      saveFailed: "Failed to save auto-switch model configuration.",
    },
    providerGroupings: {
      title: "Provider Groupings",
      description: "Group models by provider for better organization",
      enabled: "Enable Provider Groupings",
      models: "{{count}} models",
      avgLabel: "avg",
      resetLabel: "reset",
      overall: "Overall",
      healthy: "Healthy",
      degraded: "Degraded",
      limited: "Limited",
      critical: "Critical",
    },
    automation: {
      title: "Automation & Switching",
      description:
        "Configure automated session recovery and switching behaviors.",
      autoResumeChat: {
        title: "Auto-Resume Active Chat Sessions",
        description:
          "Automatically resume in-flight chat and Cascade prompts when restarting Antigravity after an account switch.",
        cliExcludedBadge: "App & IDE only",
      },
    },
    save: "Save Settings",
  },
  toast: {
    backupSuccess: {
      title: "Success",
      description: "Account backup created successfully.",
    },
    backupError: {
      title: "Error",
      description: "Failed to create backup: {{error}}",
    },
    switchSuccess: {
      title: "Success",
      description: "Switched account successfully.",
    },
    switchError: {
      title: "Error",
      description: "Failed to switch account: {{error}}",
    },
    deleteSuccess: {
      title: "Success",
      description: "Account backup deleted successfully.",
    },
    deleteError: {
      title: "Error",
      description: "Failed to delete backup: {{error}}",
    },
    chatResume: {
      successTitle: "Chat Session Resumed",
      successDesc: "Auto-resumed chat session under {{email}}.",
      failedTitle: "Auto-Resume Failed",
      failedDesc:
        "Could not auto-resume chat session. Your prompt has been saved.",
      copyPrompt: "Copy Prompt",
      promptCopied: "Prompt copied to clipboard",
    },
  },
  cloud: {
    title: "Accounts",
    description: "Manage your Google Gemini account pool.",
    summary: {
      statusUnified: "Unified (1 Active)",
      statusUnifiedSubtitle: "All environments synchronized",
      statusDiverged: "Diverged ({{count}} Targets Split)",
      statusDivergedSubtitle: "Environments running different accounts",
    },
    divergedBanner: {
      title: "Environments Desynchronized",
      description: "Environments are running different accounts: {{targets}}",
      strandedWarning:
        "Target {{target}} is stranded on a rate-limited account.",
      resyncAction: "Resync All Environments to {{email}}",
      resyncActionDefault: "Resync All Environments",
      resyncing: "Resyncing...",
    },
    security: {
      compatibilityMode: {
        title: "Compatibility key storage is active",
        description:
          "Account data remains encrypted with AES-256-GCM, but the master key is stored locally instead of being protected by the operating system credential service.",
      },
    },
    autoSwitch: "Auto-Switch",
    providerGroupings: "Provider Groupings",
    addAccount: "Add Account",
    addAccountDisabledTooltip:
      "OAuth client credentials are not configured. Set ANTIGRAVITY_OAUTH_CLIENT_ID and ANTIGRAVITY_OAUTH_CLIENT_SECRET to enable.",
    syncFromIde: "Sync from Antigravity",
    syncFromAntigravity: "Sync from Antigravity",
    checkQuota: "Check Quota Now",
    polling: "Polling triggered",
    globalQuota: "Global Quota",
    layout: {
      auto: "Auto",
      twoCol: "2 Columns",
      threeCol: "3 Columns",
      list: "List",
      compact: "Compact",
    },
    "quota-window": {
      label: "Quota window",
      "five-hours": "5-hour quota",
      "five-hours-short": "5h",
      weekly: "Weekly quota",
      "weekly-short": "Week",
      "no-weekly-quota": "No weekly quota data",
      "weekly-summary-unavailable":
        "The upstream service did not return a weekly quota summary.",
      "weekly-bucket-unavailable":
        "The quota summary contains no recognizable weekly bucket.",
    },
    authDialog: {
      title: "Add Google Account",
      description: "To add an account, you need to authorize the application.",
      missingCredentialsBanner:
        "OAuth environment variables are not configured. Adding accounts is unavailable.",
      unconfiguredWarning:
        "OAuth environment variables are not configured. Adding accounts is unavailable.",
      clientNotConfiguredBadge: "Unconfigured",
      unconfiguredBadge: "Unconfigured",
      selectedClientNotConfiguredWarning:
        "Selected OAuth client is not configured.",
      clientUnconfigured: "Selected OAuth client is not configured.",
      oauthClient: "OAuth Client",
      oauthClientPlaceholder: "Select OAuth client",
      openLogin: "Open Login Page",
      authCode: "Authorization Code",
      placeholder: "Paste the code starting with 4/...",
      instruction:
        "Will open default browser for Google login. Copy the code from localhost page and paste here.",
      verify: "Verify & Add",
    },
    localImport: {
      trigger: "Scan Local Accounts",
      title: "Import Local Accounts",
      description:
        "Scan signed-in Antigravity credentials, review verified accounts, then confirm the import.",
      scanning: "Scanning and verifying local accounts…",
      importing: "Importing the confirmed accounts…",
      summary: "Local account scan summary",
      accounts: "Accounts",
      accountList: "Discovered local accounts",
      validationFailures: "Verification failures",
      discoveryFailures: "Source failures",
      merged: "Merged",
      noAccounts: "No verified local accounts were found.",
      issues: "Items that will not be imported",
      project: "Project",
      emailCollision: "{{email}} appears in {{count}} different credentials.",
      rescan: "Scan Again",
      cancel: "Cancel",
      close: "Close",
      confirm: "Import {{count}} Accounts",
      resultTitle: "Local account import complete",
      resultDescription:
        "The account list has been updated with the confirmed result.",
      imported: "Imported {{count}}",
      skipped: "Skipped {{count}}",
      failed: "Failed {{count}}",
      sources: {
        "antigravity-keyring": "System Credential Store",
        "antigravity-app-db": "Antigravity App Database",
        "antigravity-classic-db": "Antigravity App Database",
        "antigravity-ide-db": "Antigravity IDE Database",
        "legacy-agent": "Legacy Agent Data",
        "antigravity-cli-token": "Antigravity CLI",
      },
      validationErrors: {
        "credential-unavailable": "The credential is no longer available.",
        "authentication-failed": "Google rejected this credential.",
        "network-failed":
          "The account could not be verified because of a network error.",
        "timed-out": "Account verification timed out.",
        "unverified-email": "The Google account email is not verified.",
        "invalid-profile": "Google returned an invalid account profile.",
      },
      discoveryErrors: {
        missing: "The credential source was not found.",
        "permission-denied":
          "Permission to read the credential source was denied.",
        locked: "The credential source is locked or busy.",
        malformed: "The credential source contains malformed data.",
        "timed-out": "Reading the credential source timed out.",
        "read-failed": "The credential source could not be read.",
      },
      importErrors: {
        "credential-unavailable": "The credential expired before confirmation.",
        "identity-required": "A verified account identity is required.",
        "identity-conflict":
          "This credential conflicts with an existing account identity.",
        "persistence-failed": "The account could not be saved.",
      },
      errors: {
        "preview-failed": "The local account preview could not be prepared.",
        "session-not-found": "The import session was not found. Scan again.",
        "session-expired": "The import session expired. Scan again.",
        "session-consumed": "This import session was already used. Scan again.",
        "confirmation-failed":
          "The local account import could not be completed.",
        "internal-error": "The local account import request failed.",
      },
    },
    target: {
      app: "Antigravity App",
      appShort: "App",
      classic: "Antigravity App",
      classicShort: "App",
      ide: "Antigravity IDE",
      ideShort: "IDE",
      cli: "Antigravity CLI",
      cliShort: "CLI",
      agy: "Antigravity CLI",
      agyShort: "CLI",
    },
    switch: {
      targetAll: "Switch for All Environments",
      targetAllDesc:
        "Synchronize credentials across App, IDE, and CLI in one click",
      targetAllShort: "Switch All",
      activeAll: "Active on All",
      activeAllAria: "Active across all environments: App, IDE, and CLI",
      trigger: "Switch",
      triggerAria: "Switch active account for {{email}}",
      menuTitle: "Select Target Environment",
      switchToTarget: "Switch for {{target}}",
      activeBadge: "Active",
      currentlyActiveAria: "{{target}} is currently active",
      switching: "Switching...",
      targetNotInstalled: "{{target}} is not installed on this system",
      cliHint: "Terminal tool: applies to new sessions",
      successAllToast: {
        title: "All Environments Switched",
        description: "Switched all environments to {{email}}.",
      },
      partialFailureToast: {
        title: "Partial Switch Completed",
        description:
          "Switched {{successCount}} of {{totalCount}} environments to {{email}}. Failed for {{failedTargets}}: {{error}}",
      },
      failureAllToast: {
        title: "Switch Failed",
        description: "Failed to switch environments: {{error}}",
      },
      noticeRestarted: "Credentials applied. Restarted {{target}}.",
      noticeInjectedOnDisk:
        "Credentials updated on disk for {{target}}. Changes take effect on next launch.",
      noticeCliUpdated:
        "CLI credentials updated. Ready for your next terminal command.",
      noticeBatchAllRestarted:
        "Credentials applied. Running environments have been restarted.",
      noticeBatchAllInjected:
        "Credentials updated on disk for all environments. Changes take effect on next launch.",
      noticeBatchMixed:
        "Credentials updated: restarted {{restartedTargets}}, updated on disk for {{injectedTargets}}.",
    },
    card: {
      active: "Active",
      use: "Use",
      rateLimited: "Rate Limited",
      validationRiskControlled: "Risk / Rate Limited",
      validationOAuthReauthRequired: "OAuth Re-auth Required",
      validationRequired: "Verification Required",
      completeValidation: "Verify",
      left: "left",
      used: "Used",
      unknown: "Unknown User",
      actions: "Actions",
      useAccount: "Use Account",
      identityProfile: "Identity Profile",
      refresh: "Refresh Quota",
      delete: "Delete Account",
      noQuota: "No quota data",
      rateLimitedQuota: "Rate Limited",
      liveLimitModelNotSupported: "Model not supported",
      liveLimitModelForbidden: "Model forbidden",
      liveLimitQuotaExhausted: "Quota exhausted",
      liveLimitRateLimited: "Rate limited",
      liveLimitRemaining: "{{duration}} remaining",
      liveLimitDetectedAgo: "detected {{duration}} ago",
      liveLimitActiveTitle:
        "The live upstream endpoint is temporarily unavailable.",
      liveLimitRecentTitle:
        "The live upstream endpoint recently returned an error.",
      liveLimitQuotaSnapshot:
        "The quota snapshot can still show {{percentage}}%.",
      liveLimitMessage: "Message: {{message}}",
      resetPrefix: "reset",
      resetTime: "Reset time",
      resetUnknown: "Unknown",
      detailedQuota: "Detailed quota",
      quotaGroupUnknown: "Quota group",
      gemini3Ready: "Gemini 3 Ready",
      groupGoogleGemini: "Google Gemini",
      groupAnthropicClaude: "Anthropic Claude",
      groupGpt: "GPT",
      groupOtherModels: "Other Models",
      proxy: "Proxy",
      proxyPlaceholder: "e.g. http://127.0.0.1:7890",
      proxySaved: "Proxy saved",
      noProxy: "No proxy",
      aiCredits: "AI Credits",
      aiCreditsValue: "{{amount}} credits",
      creditsExpiry: "expires {{date}}",
      modelVisibility: "Model Visibility",
    },
    identity: {
      title: "Identity Profile",
      loading: "Loading...",
      generateAndBind: "Create and Bind",
      captureAndBind: "Capture and Bind Current",
      restoreOriginal: "Restore Baseline",
      openFolder: "Open Identity Storage",
      previewTitle: "Generated Identity Preview",
      confirm: "Confirm",
      cancel: "Cancel",
      close: "Close",
      currentStorage: "Current Runtime Identity",
      accountBinding: "Bound Account Identity",
      history: "Identity History",
      noHistory: "No identity history",
      current: "Active",
      restore: "Restore",
      generateSuccess: "Identity created and bound",
      captureSuccess: "Current identity captured and bound",
      restoreOriginalSuccess: "Baseline identity restored",
      restoreVersionSuccess: "Historical identity restored",
      deleteVersionSuccess: "Historical identity deleted",
      openFolderSuccess: "Identity storage opened",
      baseline: "Baseline Identity",
    },
    list: {
      noAccounts: "No cloud accounts added yet.",
      noFilteredAccounts: "No accounts match the selected tiers.",
    },
    error: {
      loadFailed: "Failed to load cloud accounts.",
      dataRepair: {
        title: "Encrypted account data needs repair",
        description:
          "The app could not decrypt local account data. This usually means the data was created with a different encryption key or the local data is corrupted.",
        stepReLogin:
          "If key recovery still fails, re-login or re-add affected accounts without deleting the existing database.",
        stepMacPrivacy:
          "On macOS, check Keychain/privacy prompts. If the app is unsigned or was re-signed, sign it again, move it to /Applications, then reopen it.",
        stepCheckGithub:
          "Check the GitHub repository README for the latest troubleshooting steps.",
        stepOpenIssue:
          "Search GitHub Issues for this error before clearing local account data.",
        openRepository: "Open GitHub Repository",
        openIssues: "Open GitHub Issues",
      },
    },
    toast: {
      resyncSuccessTitle: "Environments Resynchronized",
      resyncSuccessDesc: "All environments synchronized to {{email}}.",
      resyncPartialTitle: "Partial Resynchronization",
      resyncPartialDesc: "Switched {{succeeded}}, but failed for {{failed}}.",
      resyncFailedTitle: "Resynchronization Failed",
      allAccountsExhaustedTitle: "All Accounts Rate-Limited",
      allAccountsExhaustedDesc:
        "All accounts in your pool are currently rate-limited. Add or wait for quota reset.",
      syncSuccess: {
        title: "Sync Successful",
        description: "Imported {{email}} from Antigravity.",
      },
      syncFailed: {
        title: "Sync Failed",
        description: "No active account found in Antigravity.",
      },
      addSuccess: "Account added successfully!",
      addFailed: {
        title: "Failed to add account",
      },
      quotaRefreshed: "Quota refreshed",
      refreshFailed: "Failed to refresh quota",
      pollFailed: "Failed to poll quota for all accounts",
      switched: {
        title: "Account switched!",
        description: "Restarting Antigravity...",
      },
      switchFailed: "Failed to switch account",
      deleted: "Account deleted",
      deleteFailed: "Failed to delete account",
      deleteConfirm: "Are you sure you want to delete this account?",
      autoSwitchOn: "Auto-Switch Enabled",
      autoSwitchOff: "Auto-Switch Disabled",
      updateSettingsFailed: "Failed to update settings",
      actionFailed: "Action failed",
      startAuthFailed: "Failed to start sign-in flow",
      refreshCreditsAvailable: "AI credits: {{amount}}",
      refreshCreditsUnavailable: "AI credits not available for this refresh.",
      batchRefreshSuccess: "Successfully refreshed {{count}} accounts.",
      batchRefreshPartial: {
        title: "Refresh completed with issues",
        description: "Refreshed {{successful}} accounts, {{failed}} failed.",
      },
      batchDeleteSuccess: "Successfully deleted {{count}} accounts.",
      batchDeletePartial: {
        title: "Deletion completed with issues",
        description: "Deleted {{successful}} accounts, {{failed}} failed.",
      },
    },
    batch: {
      selected: "Selected {{count}}",
      delete: "Delete Selected",
      refresh: "Refresh Selected",
      selectAll: "Select All",
      clear: "Clear Selection",
      confirmDelete: "Are you sure you want to delete {{count}} accounts?",
    },
    tierFilter: {
      all: "All tiers",
      reset: "Reset to all",
      selectedCount: "{{count}} tiers",
      unknown: "Unknown",
    },
    sort: {
      recentlyUsed: "Recently Used",
      quotaOverall: "Overall Quota",
      quotaClaude: "Claude Quota",
      quotaPro3: "Pro3 Quota",
      quotaFlash: "Flash Quota",
    },
    exportImport: {
      export: "Export",
      import: "Import",
      exportTitle: "Export Accounts",
      exportDesc:
        "Choose whether to include authentication tokens in the export file.",
      includeTokens: "Include tokens (less secure)",
      stripTokens: "Strip tokens (safer for sharing)",
      exportSuccess: "Accounts exported successfully",
      importTitle: "Import Accounts",
      importDesc: "Select a previously exported JSON file.",
      importStrategy: "Import Strategy",
      strategyMerge: "Merge - Update existing, add new",
      strategyOverwrite: "Overwrite - Replace all existing data",
      strategySkip: "Skip - Only add new accounts",
      importSuccess:
        "Imported {{imported}}, updated {{updated}}, skipped {{skipped}}",
      importErrors: "Import completed with {{count}} error(s)",
      selectFile: "Select File",
      importing: "Importing...",
      fileTooLarge: "File size exceeds 5MB limit",
      invalidJson: "Invalid JSON file format",
      readFileFailed: "Failed to read file",
    },
  },
  context: {
    title: "Chat Context Telemetry",
    subtitle:
      "Real-time context window usage, memory pressure, and compaction monitoring",
    badge_live: "Live",
    badge_idle: "Idle",
    badge_not_detected: "Antigravity Not Detected",
    status_normal: "Normal",
    status_high_pressure: "High Pressure",
    status_critical: "Critical Compaction Risk",
    pressure_normal: "Normal",
    pressure_high: "High Pressure",
    pressure_critical: "Critical Compaction Risk",
    metric_used: "Used Tokens",
    metric_max: "Context Ceiling",
    metric_ratio: "Context Window Utilization",
    tokens_unit: "tokens",
    cached_tokens: "Prompt Cached",
    input_tokens: "Input Tokens",
    fresh_input_tokens: "Fresh Input",
    completion_tokens: "Completion Tokens",
    thinking_tokens: "Thinking Tokens",
    output_tokens: "Output Tokens",
    active_session_title: "Active Cascade Session",
    workspace_label: "Workspace",
    session_id_label: "Session ID",
    copy_session_id: "Copy Session ID",
    session_id_copied: "Session ID copied to clipboard",
    step_count: "{{count}} turns completed",
    last_updated: "Updated {{time}}",
    subagents_title: "Active Subagents",
    subagents_active_count: "{{count}} active",
    subagents_total_tokens: "{{count}} tokens",
    subagents_toggle_aria: "Toggle active subagents list",
    subagent_role: "Subagent Role",
    subagent_tokens: "{{count}} tokens",
    switch_preview_title: "Model Switch Compatibility",
    switch_preview_subtitle:
      "Preview how your current conversation fits into alternative model context windows",
    switch_fits: "Fits Comfortably",
    switch_high_pressure: "High Memory Pressure",
    switch_overflow: "Compaction Risk: Exceeds limit by {{count}} tokens",
    model_limit_estimated: "Estimated Limit",
    model_limit_authoritative: "Verified Limit",
    compaction_detected_title: "Conversation Compacted Upstream",
    compaction_detected_desc:
      "Conversation history was compressed to fit within model limits (-{{count}} tokens at {{time}}).",
    compaction_delta_pill: "-{{count}} tokens",
    compaction_dismiss: "Dismiss Alert",
    empty_title: "No Active Conversation",
    empty_desc:
      "Start a prompt or cascade in Antigravity to view live context usage and window limits in real time.",
    empty_cta: "Open Antigravity",
    error_title: "Unable to Inspect Context Telemetry",
    error_desc:
      "Could not read active session state from your local environment. Check if Antigravity is accessible.",
    error_retry: "Retry Inspection",
    loading_title: "Reading Active Context...",
    loading_desc: "Connecting to local session telemetry...",
    concurrent_title: "Concurrent Sessions",
    no_concurrent: "No other active sessions",
    stale_warning: "Telemetry data may be momentarily delayed",
    current_model: "Current",
    stale_badge: "Stale",
    compacting_badge: "Context compacting...",
    refreshing_label: "Refreshing context...",
  },
};
export default en;
